---
title: "SSDEEP"
author: "JL"
date: "6/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r  include=FALSE,eval=FALSE}

ssdeeps = read.delim(
  "/Users/Kitty/git/fluffyDNA/prep/ssdeep/ssdeep.match.txt.gz",
  header = FALSE,
  stringsAsFactors = FALSE,
  sep = " "
)

ssdeeps$V2 = NULL
colnames(ssdeeps) = c("SEARCH", "RESULT", "SCORE")
ssdeeps$SEARCH = gsub(".consensus.txt", "", ssdeeps$SEARCH)

ssdeeps$RESULT = gsub(".consensus.txt", "", ssdeeps$RESULT)
ssdeeps$RESULT = gsub("./ssdeep/ssdeep.txt:", "", ssdeeps$RESULT)

ssdeeps$SCORE = gsub("(", "", ssdeeps$SCORE, fixed = TRUE)
ssdeeps$SCORE = gsub(")", "", ssdeeps$SCORE, fixed = TRUE)
ssdeeps$SCORE = as.numeric(ssdeeps$SCORE)

save(ssdeeps, file = "/Users/Kitty/git/fluffyDNA/prep/ssdeep/ssdeep.match.txt.Rdata")

```

```{r include=FALSE,eval=FALSE}
load("/Users/Kitty/git/fluffyDNA/prep/ssdeep/ssdeep.match.txt.Rdata")
# dcast(data = dat,formula = id~variable,fun.aggregate = sum,value.var = "value")
library(reshape2)
ssdeepsMat = dcast(
  data = ssdeeps,
  formula = SEARCH ~ RESULT,
  fun.aggregate = mean,
  value.var = "SCORE"
)
rownames(ssdeepsMat) = ssdeepsMat$SEARCH
ssdeepsMat$SEARCH = NULL

save(ssdeepsMat, file = "/Users/Kitty/git/fluffyDNA/prep/ssdeep/ssdeep.match.mat.txt.Rdata")

```


```{r include=FALSE,eval=FALSE}
# https://uc-r.github.io/hc_clustering
load("/Users/Kitty/git/fluffyDNA/prep/ssdeep/ssdeep.match.mat.txt.Rdata")
ssdeepsMat[is.na(ssdeepsMat)] <- 0
d <- dist(ssdeepsMat, method = "euclidean")

hc1 <- hclust(d, method = "complete")
save(hc1, file = "/Users/Kitty/git/fluffyDNA/prep/ssdeep/ssdeep.match.mat.hclust.Rdata")

```


## [ssdeep](https://github.com/ssdeep-project/ssdeep)



```{r}
load("/Users/Kitty/git/fluffyDNA/prep/ssdeep/ssdeep.match.txt.Rdata")
load("/Users/Kitty/git/fluffyDNA/prep/ssdeep/ssdeep.match.mat.txt.Rdata")
load("/Users/Kitty/git/fluffyDNA/prep/ssdeep/ssdeep.match.mat.hclust.Rdata")
table(ssdeeps$SEARCH == ssdeeps$RESULT)

haplogroups = read.delim(
  "/Users/Kitty/git/fluffyDNA/prep/haplogrep/haplogroups.txt",
  header = TRUE,
  stringsAsFactors = FALSE
)
hist(ssdeeps$SCORE)

plot(hc1, cex = 0.6, hang = -1)



library(plotly)
p <-
  plot_ly(
    x = ssdeeps$SEARCH,
    y = ssdeeps$RESULT,
    z = ssdeeps$SCORE,
    type = "heatmap"
  )
p
```
